// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBackendURL() {
  return window['go']['main']['App']['GetBackendURL']();
}

export function SetLastQuestion(arg1) {
  return window['go']['main']['App']['SetLastQuestion'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}
